basePath: /
definitions:
  controller.Ayam:
    properties:
      _id:
        type: string
      bobot:
        type: string
      harga:
        type: string
      jenis:
        type: string
      jenis_kelamin:
        type: string
      tinggi:
        type: string
      umur:
        type: string
    type: object
host: be-tbku1-179bbc23801d.herokuapp.com
info:
  contact:
    email: 714220039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/agung6544
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /ayam:
    get:
      consumes:
      - application/json
      description: Mengambil semua data ayam.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
      summary: Get All Data Ayam.
      tags:
      - Ayam
  /ayam/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Ayam.
      tags:
      - Ayam
schemes:
- https
- http
swagger: "2.0"
