basePath: /
definitions:
  controller.Ayam:
    properties:
      _id:
        example: "123456789"
        type: string
      bobot:
        example: "123456789"
        type: string
      harga:
        example: "12.000"
        type: string
      jenis:
        example: Ayam Saigon
        type: string
      jenis_kelamin:
        example: Jantan
        type: string
      tinggi:
        example: "123456789"
        type: string
      umur:
        example: "123456789"
        type: string
    type: object
  controller.ReqAyam:
    properties:
      bobot:
        example: "123456789"
        type: string
      harga:
        example: "12.000"
        type: string
      jenis:
        example: Ayam Saigon
        type: string
      jenis_kelamin:
        example: Jantan
        type: string
      tinggi:
        example: "123456789"
        type: string
      umur:
        example: "123456789"
        type: string
    type: object
host: be-tbku1-179bbc23801d.herokuapp.com
info:
  contact:
    email: 714220039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/agung6544
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /ayam:
    get:
      consumes:
      - application/json
      description: Mengambil semua data ayam.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
      summary: Get All Data Ayam.
      tags:
      - Ayam
  /ayam/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Ayam.
      tags:
      - Ayam
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data ayam.
      tags:
      - Ayam
  /ins:
    post:
      consumes:
      - application/json
      description: Input data ayam.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqAyam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data ayam.
      tags:
      - Ayam
  /update/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqAyam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data ayam.
      tags:
      - Ayam
schemes:
- https
- http
swagger: "2.0"
