basePath: /
definitions:
  controller.Ayam:
    properties:
      _id:
        example: "123456789"
        type: string
      bobot:
        example: 123456789
        type: integer
      harga:
        example: 12000
        type: integer
      jenis:
        example: Ayam Saigon
        type: string
      jenis_kelamin:
        example: Jantan
        type: string
      tinggi:
        example: 123456789
        type: integer
      umur:
        example: 123456789
        type: integer
    type: object
  controller.Order:
    properties:
      _id:
        type: string
      alamat:
        example: Bandung
        type: string
      ayam:
        $ref: '#/definitions/controller.Ayam'
      nama_pemesan:
        example: Dimas
        type: string
      tanggal_pemesanan:
        example: "2024-09-01T00:00:00Z"
        format: date-time
        type: string
    type: object
  controller.ReqAyam:
    properties:
      bobot:
        example: 123456789
        type: integer
      harga:
        example: 12000
        type: integer
      jenis:
        example: Ayam Saigon
        type: string
      jenis_kelamin:
        example: Jantan
        type: string
      tinggi:
        example: 123456789
        type: integer
      umur:
        example: 123456789
        type: integer
    type: object
  controller.ReqOrder:
    properties:
      alamat:
        example: Bandung
        type: string
      ayam:
        $ref: '#/definitions/controller.ReqAyam'
      nama_pemesan:
        example: Dimas
        type: string
      tanggal_pemesanan:
        example: "2024-09-01T00:00:00Z"
        format: date-time
        type: string
    type: object
host: be-tbku1-179bbc23801d.herokuapp.com
info:
  contact:
    email: 714220039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/agung6544
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /ayam:
    get:
      consumes:
      - application/json
      description: Mengambil semua data ayam.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
      summary: Get All Data Ayam.
      tags:
      - Ayam
  /ayam/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Ayam.
      tags:
      - Ayam
  /delete/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data ayam.
      tags:
      - Ayam
  /delorder/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data order.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data order.
      tags:
      - Order
  /ins:
    post:
      consumes:
      - application/json
      description: Input data ayam.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqAyam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data ayam.
      tags:
      - Ayam
  /insorder:
    post:
      consumes:
      - application/json
      description: Input data order.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Order'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data order.
      tags:
      - Order
  /order:
    get:
      consumes:
      - application/json
      description: Mengambil semua data order.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Order'
      summary: Get All Data Order.
      tags:
      - Order
  /order/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data order.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Order'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Order.
      tags:
      - Order
  /update/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data ayam.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqAyam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Ayam'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data ayam.
      tags:
      - Ayam
  /uporder/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data order.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Order'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data order.
      tags:
      - Order
schemes:
- https
- http
swagger: "2.0"
